pluginManagement {
    repositories {

        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://api.xposed.info/' }
}
    plugins {
        id("com.android.application") version "8.5.2"
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
    }
}
rootProject.name = "AA-Guard"
include(":app")
